# Shared emoji and symbol catalog.
# Keep reusable emoji-like UI constants here and import them elsewhere.

# General UI / symbols
EMOJI_BULLET = "\N{BULLET}"
EMOJI_BAR_CHART = "\N{BAR CHART}"
EMOJI_CHART_WITH_UPWARDS_TREND = "\N{CHART WITH UPWARDS TREND}"
EMOJI_BLACK_RIGHT_POINTING_TRIANGLE = "\N{BLACK RIGHT-POINTING TRIANGLE}\N{VARIATION SELECTOR-16}"
EMOJI_BLACK_RIGHT_POINTING_DOUBLE_TRIANGLE = "\N{BLACK RIGHT-POINTING DOUBLE TRIANGLE}"
EMOJI_BANKNOTE_WITH_DOLLAR_SIGN = "\N{BANKNOTE WITH DOLLAR SIGN}"
EMOJI_KEYCAP_2 = "2\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
EMOJI_WAVING_WHITE_FLAG = "\N{WAVING WHITE FLAG}\N{VARIATION SELECTOR-16}"
EMOJI_BLACK_SCISSORS = "\N{BLACK SCISSORS}\N{VARIATION SELECTOR-16}"
EMOJI_HAMMER_AND_WRENCH = "\N{HAMMER AND WRENCH}\N{VARIATION SELECTOR-16}"
EMOJI_RECYCLING_SYMBOL = "\N{BLACK UNIVERSAL RECYCLING SYMBOL}\N{VARIATION SELECTOR-16}"
EMOJI_WHITE_RIGHT_POINTING_BACKHAND_INDEX = "\N{WHITE RIGHT POINTING BACKHAND INDEX}"
EMOJI_RAISED_HAND = "\N{RAISED HAND}"
EMOJI_COLLISION_SYMBOL = "\N{COLLISION SYMBOL}"
EMOJI_STANDING_PERSON = "\U0001F9CD"
EMOJI_VICTORY_HAND = "\N{VICTORY HAND}\N{VARIATION SELECTOR-16}"
EMOJI_OCTAGONAL_SIGN = "\N{OCTAGONAL SIGN}"
EMOJI_UPWARDS_BLACK_ARROW = "\N{UPWARDS BLACK ARROW}"
EMOJI_DOWNWARDS_BLACK_ARROW = "\N{DOWNWARDS BLACK ARROW}"
EMOJI_SHIELD = "\N{SHIELD}\N{VARIATION SELECTOR-16}"
EMOJI_NO_ENTRY = "\N{NO ENTRY}"
EMOJI_SPARKLES = "\N{SPARKLES}"
EMOJI_DIRECT_HIT = "\N{DIRECT HIT}"
EMOJI_FISHING_POLE_AND_FISH = "\N{FISHING POLE AND FISH}"
EMOJI_HOOK = "\U0001FA9D"

# Card / reaction helpers
EMOJI_BLACK_SPADE_SUIT = "\N{BLACK SPADE SUIT}"
EMOJI_BLACK_HEART_SUIT = "\N{BLACK HEART SUIT}"
EMOJI_BLACK_DIAMOND_SUIT = "\N{BLACK DIAMOND SUIT}"
EMOJI_BLACK_CLUB_SUIT = "\N{BLACK CLUB SUIT}"
EMOJI_REGIONAL_INDICATOR_SYMBOL_LETTER_H = "\N{REGIONAL INDICATOR SYMBOL LETTER H}"
EMOJI_REGIONAL_INDICATOR_SYMBOL_LETTER_S = "\N{REGIONAL INDICATOR SYMBOL LETTER S}"
EMOJI_REGIONAL_INDICATOR_SYMBOL_LETTER_D = "\N{REGIONAL INDICATOR SYMBOL LETTER D}"
EMOJI_REGIONAL_INDICATOR_SYMBOL_LETTER_R = "\N{REGIONAL INDICATOR SYMBOL LETTER R}"

# Leaderboard
EMOJI_FIRST_PLACE_MEDAL = "\N{FIRST PLACE MEDAL}"
EMOJI_SECOND_PLACE_MEDAL = "\N{SECOND PLACE MEDAL}"
EMOJI_THIRD_PLACE_MEDAL = "\N{THIRD PLACE MEDAL}"

# Lotto
EMOJI_ADMISSION_TICKETS = "\N{ADMISSION TICKETS}\N{VARIATION SELECTOR-16}"
EMOJI_PARTY_POPPER = "\N{PARTY POPPER}"
EMOJI_CONFETTI_BALL = "\N{CONFETTI BALL}"
EMOJI_CLOCK_FACE_SIX_OCLOCK = "\N{CLOCK FACE SIX OCLOCK}"
EMOJI_REPEAT_ARROWS = "\N{CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS}"
EMOJI_FERRIS_WHEEL = "\N{FERRIS WHEEL}"

# Squares / circles
EMOJI_LARGE_GREEN_SQUARE = "\N{LARGE GREEN SQUARE}"
EMOJI_LARGE_YELLOW_SQUARE = "\N{LARGE YELLOW SQUARE}"
EMOJI_LARGE_RED_SQUARE = "\N{LARGE RED SQUARE}"
EMOJI_BLACK_LARGE_SQUARE = "\N{BLACK LARGE SQUARE}"
EMOJI_LARGE_GREEN_CIRCLE = "\N{LARGE GREEN CIRCLE}"
EMOJI_LARGE_BLUE_CIRCLE = "\N{LARGE BLUE CIRCLE}"
EMOJI_LARGE_PURPLE_CIRCLE = "\N{LARGE PURPLE CIRCLE}"
EMOJI_LARGE_ORANGE_CIRCLE = "\N{LARGE ORANGE CIRCLE}"
EMOJI_LARGE_RED_CIRCLE = "\N{LARGE RED CIRCLE}"
EMOJI_WHITE_CIRCLE = "\N{WHITE CIRCLE}"
EMOJI_BLACK_CIRCLE = "\N{BLACK CIRCLE}"

# Boss raids
EMOJI_HEART = "\N{BLACK HEART SUIT}\N{VARIATION SELECTOR-16}"
EMOJI_CROSSED_SWORDS = "\N{CROSSED SWORDS}\N{VARIATION SELECTOR-16}"
