# Leaderboard
EMOJI_FIRST_PLACE_MEDAL = "\N{FIRST PLACE MEDAL}"
EMOJI_SECOND_PLACE_MEDAL = "\N{SECOND PLACE MEDAL}"
EMOJI_THIRD_PLACE_MEDAL = "\N{THIRD PLACE MEDAL}"

# Wordle Reset
EMOJI_BAR_CHART = "\N{BAR CHART}"
EMOJI_CHART_WITH_UPWARDS_TREND = "\N{CHART WITH UPWARDS TREND}"

# Lotto
EMOJI_ADMISSION_TICKETS = "\N{ADMISSION TICKETS}\N{VARIATION SELECTOR-16}"
EMOJI_PARTY_POPPER = "\N{PARTY POPPER}"
EMOJI_CONFETTI_BALL = "\N{CONFETTI BALL}"
EMOJI_CLOCK_FACE_SIX_OCLOCK = "\N{CLOCK FACE SIX OCLOCK}"
EMOJI_REPEAT_ARROWS = "\N{CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS}"
EMOJI_FERRIS_WHEEL = "\N{FERRIS WHEEL}"

# Wordle
EMOJI_LARGE_GREEN_SQUARE = "\N{LARGE GREEN SQUARE}"
EMOJI_LARGE_YELLOW_SQUARE = "\N{LARGE YELLOW SQUARE}"
EMOJI_BLACK_LARGE_SQUARE = "\N{BLACK LARGE SQUARE}"
